l10n_client_contributor.settings:
  type: config_object
  label: 'Localization Client Contributor settings'
  mapping:
    use_server:
      type: boolean
      label: 'Use server'
    server:
      type: string
      label: 'Localization server url'
